name: ğŸ§ª CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    name: ğŸ¨ Format

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@364cc21a5de5b1ee4a7f5f9d3fa374ce0ccde746 # v4

      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 #v2
        with:
          bun-version: latest

      - name: ğŸ“¦ Install dependencies
        run: bun install --frozen-lockfile

      - name: ğŸ¨ Check formatting
        run: bun run format:check

  unit-tests:
    runs-on: ubuntu-latest
    name: ğŸ§ª Unit Tests (${{ matrix.workspace }})
    strategy:
      matrix:
        workspace:
          # - monitoring-idp-consumer
          - monitoring-idp-producer

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@364cc21a5de5b1ee4a7f5f9d3fa374ce0ccde746 # v4

      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 #v2
        with:
          bun-version: latest

      - name: ğŸ“¦ Install dependencies
        run: bun install --frozen-lockfile

      - name: ğŸ§ª Run tests
        working-directory: ${{ matrix.workspace }}
        run: bun test

  typecheck:
    runs-on: ubuntu-latest
    name: ğŸ” TypeCheck

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@364cc21a5de5b1ee4a7f5f9d3fa374ce0ccde746 # v4

      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 #v2
        with:
          bun-version: latest

      - name: ğŸ“¦ Install dependencies
        run: bun install --frozen-lockfile

      - name: ğŸ” Type check
        run: bun run typecheck
